swisstopo/swissgeol-assets-suite

development/init/db/clean.dump.sql

Adds an sql file to setup an initial clean DB without any  assets or otherwise critical data that needs to be private

assets #12 setup local environment and create a clean DB

---

apps/server-asset-sg/src/app/app.controller.ts

Require `master-editor` for asset sync api paths.
Amongst other things, this resolves issues with `master-editor` users crashing when accessing the page "Verwaltung".

Fix: Permissions for Elastic Sync

---

README.md
apps/client-asset-sg/src/app/app.component.html
apps/client-asset-sg/src/app/app.component.ts
apps/client-asset-sg/src/app/app.module.ts
apps/client-asset-sg/src/app/components/splash-screen/splash-screen.component.html
apps/client-asset-sg/src/app/components/splash-screen/splash-screen.component.scss
apps/client-asset-sg/src/app/components/splash-screen/splash-screen.component.ts
apps/client-asset-sg/src/app/i18n/de.ts
apps/client-asset-sg/src/app/i18n/en.ts
apps/client-asset-sg/src/app/i18n/fr.ts
apps/client-asset-sg/src/app/i18n/it.ts
apps/client-asset-sg/src/app/i18n/rm.ts
development/init/oidc/oidc-mock-users.json
libs/auth/src/lib/services/auth.interceptor.ts
libs/auth/src/lib/services/auth.service.ts
libs/client-shared/src/lib/components/button/button.component.scss

Resolves #83.
Adds a splash screen that is shown instead of the application itself whenever the user has not been authenticated yet, or when the authenticated user does not have the correct permissions.

Feature 83: Login Flow when Cancelling

---

apps/server-asset-sg/src/utils/file/common.ts
libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.html
libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.ts
libs/auth/src/lib/services/auth.interceptor.ts

Resolves #150.
Files are now first downloaded via AJAX and then exposed via ObjectURL. This allows us to authenticate the downloads with our auth token.

Feature 150: Bug - File Download schlägt fehl

---

libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.html
libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.scss
libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.ts

Resolves #167.
Displays a spinner when a file download button is pressed.

Feature 167: Add spinner to file download

---

e2e/.cypress-cucumber-preprocessorrc.json
e2e/cypress/e2e/edit-asset.feature
e2e/cypress/e2e/edit-asset/edit-asset-steps.ts
libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.html

Because the delete function is not ready yet, this pr contains only the edit asset test.

feature 147: Added edit-asset test

---

apps/client-asset-sg/docker/Dockerfile
apps/client-asset-sg/src/app/components/app-bar/app-bar.component.html
apps/client-asset-sg/src/app/components/app-bar/app-bar.component.scss
apps/client-asset-sg/src/app/components/app-bar/app-bar.component.ts
apps/client-asset-sg/tsconfig.json
libs/client-shared/src/lib/components/animate-number/animate-number.component.ts
libs/client-shared/tsconfig.json
package.json

Feature/asset #120 versions nummer

---

apps/client-asset-sg/src/app/i18n/it.ts
apps/client-asset-sg/src/app/i18n/rm.ts
libs/asset-editor/src/lib/components/asset-editor-tab-geometries/asset-editor-tab-geometries.component.ts
libs/asset-viewer/src/lib/asset-viewer.module.ts
libs/asset-viewer/src/lib/components/asset-picker/asset-picker.component.html
libs/asset-viewer/src/lib/components/asset-picker/asset-picker.component.ts
libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.html
libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.ts
libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.html
libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.scss
libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.ts
libs/asset-viewer/src/lib/components/map-controls/draw-controls.ts
libs/asset-viewer/src/lib/components/map-controls/map-controls.component.html
libs/asset-viewer/src/lib/components/map-controls/map-controls.component.scss
libs/asset-viewer/src/lib/components/map-controls/map-controls.component.ts
libs/asset-viewer/src/lib/components/map-controls/zoom-control.ts
libs/asset-viewer/src/lib/components/map/index.ts
libs/asset-viewer/src/lib/components/map/map-controller.ts
libs/asset-viewer/src/lib/components/map/map.component.html
libs/asset-viewer/src/lib/components/map/map.component.scss
libs/asset-viewer/src/lib/components/map/map.component.ts
libs/client-shared/src/lib/utils/map.ts
libs/shared/src/lib/models/study.ts

Full rewrite of the `Map` component.
Also includes various bugfixes on it (e.g. display of non-point studies, highlighting of assets via hover).

Feature 6: Improve Map Component

---

apps/server-asset-sg/src/features/asset-old/asset.service.ts
libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.html
libs/asset-viewer/src/lib/components/map/map-controller.ts
libs/asset-viewer/src/lib/models/all-study-dto.ts
libs/client-shared/src/lib/utils/map.ts
libs/shared/src/lib/models/all-study.ts

Depends on #6.
Resolves #27 
Allows study points on the map to be clicked in order to select the asset that they belong to.

Feature 27: Selection of Points

---

libs/asset-viewer/src/lib/components/asset-picker/asset-picker.component.ts
libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.html
libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.scss
libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.ts
libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.ts
libs/asset-viewer/src/lib/services/asset-search.service.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.actions.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.effects.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.reducer.ts

layout fixes for table

---

libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.html
libs/asset-viewer/src/lib/state/asset-search/asset-search.selector.ts

Fix language display in Asset Detail view

---

apps/client-asset-sg/src/app/components/splash-screen/splash-screen.component.html
libs/auth/src/lib/services/auth.service.ts

Prevent application from being visible durich login process

---

.github/workflows/code-quality.yml
e2e/cypress/e2e/create-elastic-index.feature

Re-add missing code quality steps.

Fix: Reactivate Code Quality Pipeline

---

.github/workflows/code-quality.yml
CHANGELOG.md

Add CHANGELOG.md

---

libs/asset-viewer/src/lib/components/map-controls/draw-controls.ts
libs/asset-viewer/src/lib/components/map/map.component.ts

Resolves #220.
Ignores asset clicks when a polygon is being drawn.

Feature 220: Bug - Polygon Selector öffnet Detailauswahl

---

libs/asset-viewer/src/lib/components/asset-search-refine/asset-search-refine.component.html
libs/asset-viewer/src/lib/components/asset-search-refine/asset-search-refine.component.scss

Resolves #221.
Fix author filters overflowing on new line.

Feature 221: Bug - Autoren Liste in Filtern unschön

---

libs/asset-viewer/src/lib/components/map-controls/draw-controls.ts
libs/asset-viewer/src/lib/components/map/map-controller.ts
libs/asset-viewer/src/lib/components/map/map.component.ts

Resolves #225.
Disable map click event when drawing polygon.

Feature 225: Bug - Polygon Selector öffnet Detailauswahl

---

.github/workflows/code-quality.yml
apps/client-asset-sg/docker/Dockerfile
apps/server-asset-sg/docker/Dockerfile
package-lock.json
package.json

Resolves #219.
The bug was caused by a bug in NodeJS v20. It is fixed/not present in older and newer versions. To fit it here, I bumped the Node version to v22.

Feature 219: Bug - Stats produzieren 502

---

libs/asset-viewer/src/lib/components/asset-search-refine/asset-search-refine.component.html
libs/asset-viewer/src/lib/components/asset-search-refine/asset-search-refine.component.ts

Resolves #222.
Adds a minimum date of `2018-1-1` to the `createDate` filter.

Feature 222: Anfangsdatum im Filter "Datum von" anpassen

---

apps/client-asset-sg/src/app/app.component.ts
apps/client-asset-sg/src/app/i18n/de.ts
apps/client-asset-sg/src/app/i18n/en.ts
apps/client-asset-sg/src/app/i18n/fr.ts
apps/client-asset-sg/src/app/i18n/it.ts
apps/client-asset-sg/src/app/i18n/rm.ts
apps/client-asset-sg/src/app/state/app-shared-state.service.ts
apps/client-asset-sg/src/app/state/app-shared.reducer.ts
apps/client-asset-sg/src/app/state/app.effects.ts
apps/server-asset-sg/src/app.module.ts
apps/server-asset-sg/src/features/asset-edit/asset-edit.repo.ts
apps/server-asset-sg/src/features/workgroups/workgroup-simple.repo.ts
apps/server-asset-sg/src/features/workgroups/workgroup.repo.ts
apps/server-asset-sg/src/features/workgroups/workgroups.controller.ts
apps/server-asset-sg/src/features/workgroups/workgroups.http
apps/server-asset-sg/src/main.ts
libs/asset-editor/src/lib/components/asset-editor-form-group.ts
libs/asset-editor/src/lib/components/asset-editor-tab-general/asset-editor-tab-general.component.html
libs/asset-editor/src/lib/components/asset-editor-tab-general/asset-editor-tab-general.component.ts
libs/asset-editor/src/lib/components/asset-editor-tab-page/asset-editor-tab-page.component.ts
libs/client-shared/src/lib/state/app-shared-state.actions.ts
libs/client-shared/src/lib/state/app-shared-state.selectors.ts
libs/client-shared/src/lib/state/app-shared-state.ts
libs/shared/v2/src/lib/models/workgroup.ts

Resolves #226.
Depends on #159 (PR targets that issue's branch until it is merged into `feature/workgroups`).
Adds a dropdown to the asset form with which the asset's workgroup can be selected.

Feature 226: Workgroup Dropdown on Asset

---

libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.html
libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.ts

fix reference link not updating the display of the asset detail

---

apps/client-asset-sg/src/app/app-guards.ts
apps/client-asset-sg/src/app/app.component.ts
apps/client-asset-sg/src/app/app.module.ts
apps/client-asset-sg/src/app/components/menu-bar/menu-bar.component.html
apps/client-asset-sg/src/app/components/menu-bar/menu-bar.component.ts
apps/client-asset-sg/src/app/state/app-shared.reducer.ts
apps/server-asset-sg/.env
apps/server-asset-sg/src/app.controller.ts
apps/server-asset-sg/src/core/decorators/current-user.decorator.ts
apps/server-asset-sg/src/core/middleware/jwt.middleware.ts
apps/server-asset-sg/src/features/users/users.controller.ts
apps/server-asset-sg/src/features/users/users.http
apps/server-asset-sg/src/features/workgroups/workgroup-simple.repo.ts
libs/auth/src/lib/services/auth.interceptor.ts
libs/auth/src/lib/services/auth.service.ts
libs/client-shared/src/lib/state/app-shared-state.actions.ts
libs/client-shared/src/lib/state/app-shared-state.selectors.ts
libs/client-shared/src/lib/state/app-shared-state.ts
package-lock.json
package.json

resolves #247 
To test this, set REQUIRES_AUTHORIZATION=false in the .env file.
This will bypass the oauth flow both in the frontend and backend and create/use an anonymous user in the DB

add viewer mode

---

apps/server-asset-sg/src/core/middleware/jwt.middleware.ts
libs/asset-viewer/src/lib/components/map/map.component.ts

Handle emails which include underscores, remove duplicate code in map

---

apps/client-asset-sg/src/app/components/menu-bar/menu-bar.component.html
apps/server-asset-sg/.env
apps/server-asset-sg/src/app.module.ts
apps/server-asset-sg/src/features/assets/asset.repo.ts
apps/server-asset-sg/src/features/assets/search/asset-search.service.ts
apps/server-asset-sg/src/features/assets/sync/asset-sync.controller.ts
apps/server-asset-sg/src/features/assets/sync/asset-sync.service.ts
package-lock.json
package.json

Automatically sync search index

---

apps/server-asset-sg/src/features/assets/search/asset-search.service.ts

Fix search filter stats

---

libs/asset-viewer/src/lib/components/map-controls/draw-controls.ts
libs/asset-viewer/src/lib/components/map/map.component.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.effects.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.reducer.ts
libs/core/src/lib/utils/eq.ts

Retain detail with polygons

---

apps/client-asset-sg/src/app/i18n/de.ts
apps/client-asset-sg/src/app/i18n/en.ts
apps/client-asset-sg/src/app/i18n/fr.ts
apps/client-asset-sg/src/app/i18n/it.ts
apps/client-asset-sg/src/app/i18n/rm.ts
libs/asset-viewer/src/lib/asset-viewer.module.ts
libs/asset-viewer/src/lib/components/asset-search-refine/asset-search-refine.component.html
libs/asset-viewer/src/lib/components/asset-search-refine/asset-search-refine.component.ts
libs/asset-viewer/src/lib/components/map-controls/draw-controls.ts
libs/asset-viewer/src/lib/components/map-controls/map-controls.component.html
libs/asset-viewer/src/lib/components/map-controls/map-controls.component.scss
libs/asset-viewer/src/lib/components/map-controls/map-controls.component.ts
libs/asset-viewer/src/lib/components/map/map.component.html
libs/asset-viewer/src/lib/components/map/map.component.ts
libs/asset-viewer/src/lib/state/map-control/map-control.actions.ts
libs/asset-viewer/src/lib/state/map-control/map-control.reducer.ts
libs/asset-viewer/src/lib/state/map-control/map-control.selector.ts
libs/client-shared/src/lib/components/button/button.component.scss

Move polygon button to filter pane

---

apps/server-asset-sg/src/core/authorize.ts
apps/server-asset-sg/src/features/asset-edit/asset-edit.controller.ts
apps/server-asset-sg/src/features/assets/assets.controller.ts
apps/server-asset-sg/src/features/workgroups/workgroup-simple.repo.ts
libs/asset-editor/src/lib/asset-editor.module.ts
libs/client-shared/src/lib/directives/base-policy.directive.ts
libs/shared/v2/src/lib/policies/asset-edit.policy.ts
libs/shared/v2/src/lib/policies/asset.policy.ts
libs/shared/v2/src/lib/policies/base/policy.ts
libs/shared/v2/src/lib/policies/contact.policy.ts
libs/shared/v2/src/lib/policies/workgroup.policy.ts

Prevent admins from editing in workgroups they are no members of

---

apps/server-asset-sg/src/features/workgroups/workgroup-simple.repo.ts

Fix bug for non-admin users

---

apps/client-asset-sg/src/app/i18n/de.ts
apps/client-asset-sg/src/app/i18n/en.ts
apps/client-asset-sg/src/app/i18n/fr.ts
apps/client-asset-sg/src/app/i18n/it.ts
apps/client-asset-sg/src/app/i18n/rm.ts
apps/server-asset-sg/src/core/exception-filters/prisma.exception-filter.ts
apps/server-asset-sg/src/main.ts
libs/admin/src/lib/state/admin.effects.ts
libs/auth/src/lib/services/auth.interceptor.ts
libs/client-shared/src/lib/features/alert/alert.model.ts
libs/client-shared/src/lib/features/alert/alert/alert.component.html
libs/client-shared/src/lib/features/alert/alert/alert.component.ts

Feature 238: Fehler bei gleichem Workgroup-Namen ordentlich anzeigen

---

apps/client-asset-sg/src/app/i18n/de.ts
apps/client-asset-sg/src/app/i18n/en.ts
apps/client-asset-sg/src/app/i18n/fr.ts
apps/client-asset-sg/src/app/i18n/it.ts
apps/client-asset-sg/src/app/i18n/rm.ts
apps/server-asset-sg/src/features/files/file-ocr.service.ts
libs/asset-editor/src/lib/components/asset-editor-tab-contacts/asset-editor-tab-contacts.component.html
libs/asset-editor/src/lib/components/asset-editor-tab-contacts/asset-editor-tab-contacts.component.scss
libs/asset-editor/src/lib/components/asset-editor-tab-contacts/asset-editor-tab-contacts.component.ts

Feature 294: Autocomplete für Autoren im Edit-Asset Formular

---

apps/client-asset-sg/src/app/app.module.ts
apps/client-asset-sg/src/app/components/redirect-to-lang/redirect-to-lang.component.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.effects.ts
libs/auth/src/lib/services/auth.service.ts

asset.viewer displayed the not found page, when opening the page without any lang parameter du to changes to the routing

revert the changes that removed the RedirectToLangComponent 

---

libs/asset-viewer/src/lib/state/asset-search/asset-search.effects.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.selector.ts

Fix 346: Reset favoritesOnly and fix display of heatmap

---

apps/server-asset-sg/src/features/asset-edit/asset-edit.repo.ts

Fix 348: Remove deletions of assetKindItems and assetFormatItem

---

libs/client-shared/src/lib/components/disclaimer-dialog/disclaimer-dialog.component.ts

Fix 347: Missing Link in Disclaimer

---

.editorconfig
scripts/2024-10-01_import-new-geometries/main.py

assets 270 geometries

---

README.md

Update the tables to exclude from the origin db when creating a new dump

Update README.md for db dump creation

---

apps/client-asset-sg/project.json
libs/asset-viewer/src/lib/components/map/map.component.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.effects.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.selector.ts
package-lock.json

Bugfix 356: Studies verschwinden, wenn man ein Detail anwählt

---

libs/asset-editor/src/lib/asset-editor.module.ts
libs/asset-editor/src/lib/components/asset-editor-id-form/asset-editor-id-form.component.html
libs/asset-editor/src/lib/components/asset-editor-id-form/asset-editor-id-form.component.scss
libs/asset-editor/src/lib/components/asset-editor-id-form/asset-editor-id-form.component.ts
libs/asset-editor/src/lib/components/asset-editor-id-list/asset-editor-id-list.component.html
libs/asset-editor/src/lib/components/asset-editor-id-list/asset-editor-id-list.component.scss
libs/asset-editor/src/lib/components/asset-editor-id-list/asset-editor-id-list.component.ts
libs/asset-editor/src/lib/components/asset-editor-tab-general/asset-editor-tab-general.component.html
libs/asset-editor/src/lib/components/asset-editor-tab-general/asset-editor-tab-general.component.ts

Resolves #335.
This is basically just a complete rewrite of the ids section in the asset form.
The section was really convoluted and basically not worth to fix as-is.
Now, ids are displayed and edited in two separate components, which should be much easier to understand and change in the future.

Feature 335: Bug - Alternativ Ids

---

libs/persistence/prisma/migrations/20250129081408_unique_constraint_for_sgs_id/migration.sql
libs/persistence/prisma/schema.prisma

add unique constraint for sgs id

---

libs/asset-editor/src/lib/components/asset-editor-tab-contacts/asset-editor-tab-contacts.component.html
libs/asset-editor/src/lib/components/asset-editor-tab-contacts/asset-editor-tab-contacts.component.ts

Fix 336: Derselbe Kontakt mit verschiedenen Rollen kann nicht einzeln gelöscht werden

---

apps/client-asset-sg/docker/Dockerfile
apps/server-asset-sg/docker/Dockerfile
apps/sync-asset-sg/docker/Dockerfile

Fix 403: Sync Service is Broken

---

apps/client-asset-sg/src/app/app.module.ts
apps/client-asset-sg/src/app/components/app-bar/app-bar.component.ts
apps/client-asset-sg/src/app/components/redirect-to-lang/redirect-to-lang.component.ts
apps/client-asset-sg/src/app/state/app.effects.ts
libs/asset-editor/src/lib/components/asset-editor-tab-page/asset-editor-tab-page.component.ts
libs/asset-editor/src/lib/state/asset-editor.effects.ts
libs/asset-viewer/src/lib/asset-viewer.module.ts
libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.html
libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.ts
libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.ts
libs/asset-viewer/src/lib/services/viewer-params.service.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.effects.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.reducer.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.selector.ts
libs/client-shared/src/lib/services/routing.service.ts
libs/client-shared/src/lib/state/app-shared-state.actions.ts

Feature 386: Löschen von Asset führt zu Endlosschlaufe

---

apps/server-asset-sg/src/features/users/user.repo.ts
e2e/cypress/e2e/common/login.ts

adds the first and lastname of a user to the database if it already exists

update the first and last name of a user correctly

---

libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.html
libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.scss

replace break-word with overflow-wrap

---

libs/asset-viewer/src/lib/asset-viewer.module.ts
libs/asset-viewer/src/lib/components/asset-viewer-files/asset-viewer-files.component.html
libs/asset-viewer/src/lib/components/asset-viewer-files/asset-viewer-files.component.ts
libs/asset-viewer/src/lib/components/asset-viewer-files/file-size-display.pipe.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.selector.ts

add filesize pipe

---

apps/client-asset-sg/src/app/app.component.ts
apps/server-asset-sg/src/features/users/user.service.ts
libs/admin/src/lib/components/workgroup-edit/workgroup-edit.component.html
libs/admin/src/lib/components/workgroup-edit/workgroup-edit.component.scss
libs/asset-editor/src/lib/components/asset-editor-tab-administration/asset-editor-tab-administration.component.html
libs/asset-editor/src/lib/components/asset-editor-tab-administration/asset-editor-tab-administration.component.ts

Resolves Bugs on INT as reported by @mPfifi.
Fixed:
- Delete button on asset edit screen was always disabled
- API crashed periodically due to user sync being rate limited by Cognito
- Inactive overlay on workgroups did not cover the part of the page after the scroll break

Hotfix: Pre-Release Bugs

---

libs/admin/src/lib/components/admin-page/admin-page.component.html
libs/admin/src/lib/components/admin-page/admin-page.component.ts
libs/admin/src/lib/components/user-edit/user-edit.component.ts
libs/admin/src/lib/state/admin.actions.ts
libs/admin/src/lib/state/admin.reducer.ts

Fix bug that displayed the wrong language for users

---

libs/asset-viewer/src/lib/components/map-legend/map-legend.component.scss
libs/client-shared/src/lib/icons/map-styles/access.ts
libs/client-shared/src/lib/icons/map-styles/geometry.ts

Provided by Simon; also note the changed gaps/directions.

Assets-299: Add proper icons; fix styling

---

apps/client-asset-sg/docker/nginx.conf
apps/server-asset-sg/src/main.ts
package-lock.json
package.json

resolves #440 
uses default config of [helmet](https://helmetjs.github.io/)

add helmet with default config

---

apps/server-asset-sg/src/features/files/files.controller.ts
libs/asset-editor/src/lib/components/asset-editor-files/asset-editor-files.component.ts

update filesize to 2GB

---

apps/client-asset-sg/docker/nginx.conf

resolves #440 
add Content-Security-Policy, Permissions-Policy and Referrer-Policy headers

add two additional headers to nginx config

---

apps/client-asset-sg/src/app/components/menu-bar/menu-bar.component.ts
apps/server-asset-sg/src/features/files/file-ocr.service.ts
apps/server-asset-sg/src/utils/sleep.ts
libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.ts
libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.ts
libs/asset-viewer/src/lib/components/map/map-controller.ts
libs/asset-viewer/src/lib/components/map/map.component.ts
libs/asset-viewer/src/lib/services/viewer-params.service.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.actions.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.effects.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.reducer.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.selector.ts
libs/client-shared/src/lib/services/routing.service.ts
libs/client-shared/src/lib/state/app-shared-state.actions.ts
libs/shared/v2/src/index.ts
libs/shared/v2/src/lib/utils/object.ts
libs/shared/v2/src/lib/utils/sleep.ts

Feature 302: Position der Suchergebnisse beibehalten

---

apps/client-asset-sg/docker/nginx.conf

remove CSP Header

---

apps/client-asset-sg/src/app/i18n/de.ts
apps/client-asset-sg/src/app/i18n/en.ts
apps/client-asset-sg/src/app/i18n/fr.ts
apps/client-asset-sg/src/app/i18n/it.ts
libs/client-shared/src/lib/components/disclaimer-dialog/disclaimer-dialog.component.html
libs/client-shared/src/lib/components/disclaimer-dialog/disclaimer-dialog.component.scss
libs/client-shared/src/lib/components/disclaimer-dialog/disclaimer-dialog.component.ts
libs/client-shared/src/lib/components/language-selector/language-selector.component.html
libs/client-shared/src/lib/components/language-selector/language-selector.component.ts
libs/client-shared/src/lib/features/auth/auth.service.ts

Resolves #432.
Aligns the contents of the disclaimer with boreholes.

Feature 432: Integration/Aktivierung GoogleAnalytics

---

apps/client-asset-sg/src/app/components/menu-bar/menu-bar.component.html
apps/client-asset-sg/src/app/components/menu-bar/menu-bar.component.ts
libs/asset-editor/src/lib/components/asset-editor-launch/asset-editor-launch.component.ts
libs/asset-viewer/src/lib/asset-viewer.module.ts
libs/asset-viewer/src/lib/components/asset-picker/asset-picker.component.ts
libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.html
libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.ts
libs/asset-viewer/src/lib/components/asset-search-filter/asset-search-filter.component.ts
libs/asset-viewer/src/lib/components/asset-search-refine/asset-search-refine.component.ts
libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.ts
libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.html
libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.ts
libs/asset-viewer/src/lib/components/map/map-controller.ts
libs/asset-viewer/src/lib/components/map/map.component.ts
libs/asset-viewer/src/lib/services/all-study.service.ts
libs/asset-viewer/src/lib/services/viewer-controller.service.ts
libs/asset-viewer/src/lib/services/viewer-params.service.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.actions.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.effects.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.reducer.ts
libs/asset-viewer/src/lib/state/asset-search/asset-search.selector.ts
libs/client-shared/src/lib/directives/base-policy.directive.ts
libs/client-shared/src/lib/state/app-shared-state.actions.ts
libs/shared/src/lib/models/asset-search/asset-search-query.ts
libs/shared/src/lib/models/asset-search/asset-search-result.ts

Resolves #302.
Refactor effects of viewer into `ViewerControllerService` for easier management of the loading behavior.

Feature #302: Position der Suchergebnisse beibehalten

---

CHANGELOG.md

add changelog for new  release

update changelog for 1.10.0

---

libs/client-shared/src/lib/components/disclaimer-dialog/disclaimer-dialog.component.ts

Feature 479: Datenschutz-Links im Disclaimer anpassen

---

apps/client-asset-sg/src/app/components/google-analytics/google-analytics.component.ts

Fixes an issue where google analytics was included, but did not submit any data.
This was due to the analytics setup having been customized. While the previous solution had effectively the same behavior, some very minor (and, too large parts, unclear) parts caused the analytics script to ignore its configuration.
This PR fixes the issues by simply using the plain, official JS code to configure the analytics.
**Note:** This is a hotfix and thus merges directly into `main`.

Hotfix: Inclusion of Google Analytics

---

apps/client-asset-sg/docker/Dockerfile
apps/server-asset-sg/docker/Dockerfile
apps/sync-asset-sg/docker/Dockerfile

Fix npm install permission in Dockerfiles

---

LICENSE

Hallo @vej-ananas 
Wie heute besprochen, hier der PR zum Lizenz-File. 
#530

license file added

---

apps/client-asset-sg/src/app/services/http.interceptor.ts
libs/client-shared/src/lib/features/alert/alert/alert.component.scss

Bugix 568: Fehlende Files führen zu Endlosschlaufe ohne Fehler

---

apps/client-asset-sg/src/app/i18n/de.ts
apps/client-asset-sg/src/app/i18n/en.ts
apps/client-asset-sg/src/app/i18n/fr.ts
apps/client-asset-sg/src/app/i18n/it.ts
apps/client-asset-sg/src/app/services/http.interceptor.ts
development/.gitignore
libs/asset-viewer/src/lib/components/asset-viewer-files/asset-viewer-files.component.ts

Bugfix 568: Fehlende Files führen zu Endlosschlaufe ohne Fehler

---

README.md
apps/server-asset-sg/src/features/assets/asset-edit/asset-edit.controller.ts
apps/server-asset-sg/src/features/assets/assets/assets.controller.ts
apps/server-asset-sg/src/features/assets/workflow/workflow.service.ts
libs/asset-editor/src/lib/components/asset-editor-page/asset-editor-page.component.ts
libs/asset-editor/src/lib/state/asset-editor.actions.ts
libs/asset-editor/src/lib/state/asset-editor.effects.ts
libs/shared/v2/src/lib/models/workflow.ts

Resolves #581.
Depends on #586.

Feature 581: Reset Review & Published Häkchen wenn editiert wird

---

apps/server-asset-sg/src/features/assets/asset.service.ts

Use updatedAsset to update elastic search when editing an asset

---

libs/asset-viewer/src/lib/services/viewer-controller.service.ts

Bugfix 644: Vorangehende Ansicht geht bei Wechsel in Edit-Modus und zurück teilweise verloren

---

apps/server-asset-sg/src/features/assets/workflow/workflow.service.ts
libs/asset-editor/src/lib/components/asset-editor-tabs/asset-editor-status/asset-editor-status.component.ts
libs/asset-editor/src/lib/services/workflow-api.service.ts

Approval checkboxes are unchecked when review checkboxes are modified after staus has changed back to review. 
Required changes to core lib: https://github.com/swisstopo/swissgeol-ui-core/pull/74

Assets 653: Freigabe Haken

---

libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.html
libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.ts

Hide workflow attributes in anonymous mode

---

apps/client-asset-sg/src/app/i18n/de.ts
apps/client-asset-sg/src/app/i18n/en.ts
apps/client-asset-sg/src/app/i18n/fr.ts
apps/client-asset-sg/src/app/i18n/it.ts
apps/server-asset-sg/src/features/assets/files/file-processors/file-extraction.service.ts
development/docker-compose.yaml
k8s/swissgeol-assets/templates/deployment.api.yaml
k8s/swissgeol-assets/templates/deployment.dataextraction.yaml
k8s/swissgeol-assets/templates/service-account.dataextraction.yaml
k8s/swissgeol-assets/templates/service.dataextraction.yaml
k8s/swissgeol-assets/values.template.yaml
libs/shared/v2/src/lib/models/asset-file.ts

Resolves #674.
TODOs before merging:
- ~Use new service account instead of reusing the OCR's (see https://jira.swisstopo.ch/projects/IGI_SB/issues/IGI_SB-4234).~ We haven't got that account yet, but want to deploy either way. We're reusing the OCR account for now.

Feature 674: Deploy API
