swisstopo/swissgeol-assets-suite

- libs/admin/src/lib/components/admin-page/admin-page.component.scss
- libs/asset-editor/src/lib/components/asset-editor-tab-administration/asset-editor-tab-administration.component.html
- libs/asset-editor/src/lib/components/asset-editor-tab-administration/asset-editor-tab-administration.component.ts
- libs/asset-editor/src/lib/components/asset-editor-tab-contacts/asset-editor-tab-contacts.component.html
- libs/asset-editor/src/lib/components/asset-editor-tab-contacts/asset-editor-tab-contacts.component.ts
- libs/asset-editor/src/lib/components/asset-editor-tab-general/asset-editor-tab-general.component.html
- libs/asset-editor/src/lib/components/asset-editor-tab-general/asset-editor-tab-general.component.ts
- libs/asset-editor/src/lib/components/asset-editor-tab-page/asset-editor-tab-page.component.scss
- libs/asset-editor/src/lib/components/asset-editor-tab-references/asset-editor-tab-references.component.ts
- libs/asset-editor/src/lib/components/asset-editor-tab-usage/asset-editor-tab-usage.component.html
- libs/asset-editor/src/lib/components/asset-editor-tab-usage/asset-editor-tab-usage.component.scss
- libs/asset-editor/src/lib/components/asset-multiselect/asset-multiselect.component.ts
- libs/asset-editor/src/lib/services/asset-editor.service.ts
- libs/asset-editor/src/lib/state/asset-editor.effects.ts
- libs/client-shared/src/lib/components/drag-handle/drag-handle.component.ts
- libs/core/src/lib/utils/array.ts
- libs/ngx-kobalte/src/lib/components/tabs.ts
Added Scrollbars to the following places as defined in Ticket #8 :
User Management
Asset Editor Pages
> Feature/assets 8: add missing scrollbars

- apps/client-asset-sg/src/styles.scss
- libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.html
- libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.html
To test this, search for "laaaaaaaaaaaaaannnnnnngggggggggeeeerrrrrrTiteeeeeeeeeLLLLLLLLL" in the searchbar, and select the element (created with admin@assts.sg user).
The title is now on multiple lines and the edit button still visibile
> assets-32: break long titles so the edit button is not hidden

- apps/client-asset-sg-e2e/src/support/commands.ts
I just removed the password from the console log to get rid of the security warning. 
We could also remove those files altogether, but maybe that is paart of a bigger cleanup.
@ga-ebp what are your thoughts on this?
> assets-39: remove console log of password from test

- apps/server-asset-sg/docker/Dockerfile
- apps/server-asset-sg/docker/start.sh
Resolves #73.
Replaces the startup command of the API's Docker image with a shell script that runs `prisma migrate deploy` before starting the application itself.
> Feature 73: CI/CD for Database Changes

- apps/client-asset-sg/project.json
- apps/server-asset-sg/src/app/app.service.ts
- apps/server-asset-sg/src/app/asset-edit/asset-edit.service.ts
- apps/server-asset-sg/src/app/models/AssetDetailFromPostgres.ts
- apps/server-asset-sg/src/app/models/asset-edit-detail.ts
- apps/server-asset-sg/src/app/prisma/migrations/20240418060636_multi_language_assets/migration.sql
- apps/server-asset-sg/src/app/prisma/schema.prisma
- apps/server-asset-sg/src/app/scripts/export-to-elasticsearch.ts
- apps/server-asset-sg/src/app/search/find-assets-by-search-text.ts
- apps/server-asset-sg/src/app/search/search-asset.ts
- libs/shared/src/lib/models/SearchAssetResult.ts
- libs/shared/src/lib/models/asset-detail.ts
- libs/shared/src/lib/models/asset-edit.ts
- libs/shared/src/lib/models/elastic-search-asset.ts
- libs/shared/src/lib/models/patch-asset.ts
Resolves #78, part of #29.
Replaces the `languageItemCode` of assets in the database and API with a many-to-many relationship.
> Feature 78: Multi-Language - Backend & Database

- libs/asset-editor/src/lib/components/asset-editor-tab-general/asset-editor-tab-general.component.ts
Resolves #33.
The bug can reproduced simply by adding a new alternative id, and then editing + saving an existing one. This will cause the id that is being edited to be removed from the form.
**Cause:**  
The fields used to create/edit an alternative id are in a standalone form (i.e. it's not part of the big form that controls the entire asset view). Instead, it's a small form that is "manually" synced back to the big form via observables. This is quite an opaque task with a lot of corner cases. In this case, a subscriber that syncs the two forms was triggered after saving the existing id, but before resetting the small form back to a non-edit state. This caused the subscriber to perceive the id as being "new", and the form as "cancelled", which is why it removes the "cancelled" id. …
> Feature 33: Bug - Alternativ-ID's werden nicht gespeichert

- apps/server-asset-sg/project.json
Always use the `production` configuration when running the `server-asset-sg:build` command.
> Hotfix: Build with Production Configuration

- apps/server-asset-sg/project.json
Adds all Prisma migrations to the server's build output, so they can be used to migrate database from within any deployed API images.
> Fix: Add prisma migrations to server build output

- apps/server-asset-sg/src/app/search/asset-search-service.ts
Allows for lookups on specific Elasticsearch fields by treating queries that contain `:` differently from normal searches.
> Fix: Search with `sgsId` does not find correct result

- apps/server-asset-sg/src/app/search/asset-search-service.ts
Allow searches on specific fields to use case-insensitive field names by normalizing the names before running the search.
> Fix: Case Insensitive Search

- .github/actions/create-image/action.yaml
- .github/actions/tag-commit/action.yaml
- .github/scripts/find-version.js
- .github/scripts/remove-packages.js
- .github/workflows/code-quality.yml
- .github/workflows/codeql.yml
- .github/workflows/publish-edge.yml
- .github/workflows/publish-rc.yml
- .github/workflows/release.yml
- apps/client-asset-sg/docker/Dockerfile
- apps/server-asset-sg/docker/Dockerfile
- development/docker-compose.yaml
- development/init/oidc/oidc-mock-scopes.json
- development/init/oidc/oidc-mock-server_options.json
Resolves #123.
Depends on #137.
**New Workflows**
Updates all current workflows to be aligned closer to boreholes' DevOps suite.
- `CodeQL` remains as is.
- `Code Quality` runs whenever a Pull Request is created or changed. It ensures that the code within the PR is up to standard and fully operational.
- `Publish Edge` runs whenever `develop` is pushed to. It builds a new Docker image for both `app` and `api` and tags it with `edge`. It also generates a development version tag based formatted like `X.X.X-devX`, which ensures that the image is addressable even if `edge` is moved to a newer image.
- `Publish Release Candidate` runs whenever `main` is pushed to. It adds the `release-candidate` tag to the current `edge` images.
- `Relase` has to be run manually. It builds release versions of …
> Feature 123: Devops-Angleich

- apps/client-asset-sg/src/app/i18n/de.ts
- apps/client-asset-sg/src/app/i18n/en.ts
- apps/client-asset-sg/src/app/i18n/fr.ts
- apps/client-asset-sg/src/app/i18n/it.ts
- apps/client-asset-sg/src/app/i18n/rm.ts
- apps/server-asset-sg/jest.config.ts
- apps/server-asset-sg/src/features/assets/search/asset-search.service.spec.ts
- apps/server-asset-sg/src/features/assets/search/asset-search.service.ts
- libs/asset-viewer/src/lib/asset-viewer.module.ts
- libs/asset-viewer/src/lib/components/asset-search-filter-list/asset-search-filter-list.component.html
- libs/asset-viewer/src/lib/components/asset-search-filter-list/asset-search-filter-list.component.scss
- libs/asset-viewer/src/lib/components/asset-search-filter-list/asset-search-filter-list.component.ts
- libs/asset-viewer/src/lib/components/asset-search-refine/asset-search-refine.component.html
- libs/asset-viewer/src/lib/components/asset-search-refine/asset-search-refine.component.scss
- libs/asset-viewer/src/lib/components/asset-search-refine/asset-search-refine.component.ts
- libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.ts
- libs/asset-viewer/src/lib/state/asset-search/asset-search.actions.ts
- libs/asset-viewer/src/lib/state/asset-search/asset-search.effects.ts
- libs/asset-viewer/src/lib/state/asset-search/asset-search.reducer.ts
- libs/asset-viewer/src/lib/state/asset-search/asset-search.selector.ts
- libs/client-shared/src/lib/components/index.ts
- libs/client-shared/src/lib/components/smart-translate.pipe.ts
- libs/shared/src/lib/models/asset-search/asset-search-query.dto.ts
- libs/shared/src/lib/models/asset-search/asset-search-query.ts
Resolves #138.
Adds the `None` language item to ElasticSearch assets that don't have any languages assigned to them.
Also, the filter selectors of the asset-search state have been refactored so that filters that rely on static values can be used the same as filters that use database values.
> Feature 138: Filter "Keine Sprache" bei Suchfiltern

- libs/asset-viewer/src/lib/services/all-study.service.ts
- libs/shared/src/lib/models/lv95.ts
Fixed studies not being displayed on the map.
The issue was that when parsing the studies' center coordinates from the DB, the x and y coordinates must be switched, which no longer happened in the latest version.
> Fix: Studies missing from map

- package.json
The `develop` build is missing some NX build dependencies used when building the app's Docker images. This PR adds them.
> Fix: Add missing optional NX dependencies used by docker build

- README.md
- libs/asset-viewer/src/lib/services/all-study.service.ts
- package.json
Resolves #230.
Fixes an issue where all studies, no matter if point or non-point, where displayed as points.
Note that this PR also includes some small additions (which were, for the most part, long overdue). These are:
- Updating the data import command in `README.md` to stop on the first error. Without this, it's often hard to notice if something went wrong when importing data.
- Update the `prisma` npm script to also read `.env.local`, which allows easier handling of database-related environment variables in our local development environments.
> Feature 230: Bug - Rauten von Studies

- apps/pipeline-asset-sg/src/core/export-to-view.service.ts
- libs/persistence/prisma/schema.prisma
- package.json
Remove legal doc distinction in file export - they are now in a separate table
Add `native` to Prisma's `binaryTargets`
Add `pipeline-asset-sg` to the `build` command
> Fix: Pipeline Build

- apps/server-asset-sg/src/app.logger.ts
Fixes errors of type `UnknownError` being logged as `undefined` instead of displaying their stack trace.
> Fix unknown error logging

- apps/server-asset-sg/src/features/asset-edit/asset-edit.controller.ts
- apps/server-asset-sg/src/features/asset-edit/asset-edit.http
- libs/asset-editor/src/lib/components/asset-editor-tab-usage/asset-editor-tab-usage.component.ts
- libs/shared/v2/src/lib/models/user.ts
> Fix: don't allow to update usage status or work status if not masterEditor

- libs/asset-viewer/src/lib/components/map-controls/zoom-control.ts
- libs/asset-viewer/src/lib/components/map/map-controller.ts
- libs/client-shared/src/lib/utils/map.ts
- tsconfig.base.json
> Feature 296: Gesamte Schweiz auch auf kleineren Laptop Bildschirmen sichtbar machen

- libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.html
- libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.ts
- libs/asset-viewer/src/lib/components/asset-search-filter-list/asset-search-filter-list.component.ts
- libs/asset-viewer/src/lib/components/asset-search-refine/asset-search-refine.component.ts
- libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.html
- libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.ts
- libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.ts
- libs/asset-viewer/src/lib/components/map/map.component.ts
- libs/asset-viewer/src/lib/services/asset-search.service.ts
- libs/asset-viewer/src/lib/state/asset-search/asset-search.actions.ts
- libs/asset-viewer/src/lib/state/asset-search/asset-search.effects.ts
- libs/asset-viewer/src/lib/state/asset-search/asset-search.reducer.ts
- libs/asset-viewer/src/lib/state/asset-search/asset-search.selector.ts
Rewrites the search effects to fix any remaining errors with the search parameters and to make handling the entire search easier.
Behaviour should not be changed from DEV.
> Hotfix: Clear Selected Asset in Search

- apps/server-asset-sg/docker/Dockerfile
- apps/server-asset-sg/src/app.module.ts
- apps/server-asset-sg/src/features/users/user.repo.ts
- apps/server-asset-sg/src/features/users/user.service.ts
- apps/server-asset-sg/src/utils/file/common.ts
- apps/server-asset-sg/src/utils/requireEnv.ts
- libs/persistence/prisma/migrations/20250113162002_cascade_user_deletion/migration.sql
- libs/persistence/prisma/schema.prisma
- package-lock.json
- package.json
Resolves #292.
See also [https://github.com/swisstopo/swissgeol-assets-config/pull/4].
Note that for a full deployment, INT and PROD need to have their own service accounts for Cognito.
I'm in contact with the Cloud Team regarding these accounts.
> Feature 292: Benutzer Löschen

- libs/asset-editor/src/lib/components/asset-editor-tab-page/asset-editor-tab-page.component.html
- libs/asset-editor/src/lib/components/asset-editor-tab-page/asset-editor-tab-page.component.ts
- libs/client-shared/src/lib/services/index.ts
- libs/client-shared/src/lib/services/routing.service.ts
> Feature 332: Schliessen (x) im Editiermodus soll zur vorigen Seite führen

- apps/client-asset-sg/docker/Dockerfile
- apps/server-asset-sg/docker/Dockerfile
Generates prisma source files before compiling in docker builds.
> Hotfix: Docker Builds Failing due to Missing Prisma Source Files

- package.json
Reorders lint commands to always run eslint before prettier.
> Fix: Order of Lint Commands

- .github/workflows/publish-edge.yml
- libs/asset-viewer/src/lib/services/viewer-controller.service.ts
- libs/client-shared/src/lib/components/disclaimer-dialog/disclaimer-dialog.component.ts
Resolves #437.
Depends on #479 (mainly to enable a complete DEV deployment from this branch)
Fixes an issue where the value for the `favoritesOnly` was taken from the store (i.e. the last used value) instead of from the URL. This could cause the `/favorites` page to show non-favorited assets, and in turn, cause `/` to show only favorites.
Note that this PR targets `main` instead of `develop`, in order to create a release candidate without including #299 and its colleagues.
> Feature 437: Ermögliche Permalinks

- k8s/swissgeol-assets/templates/deployment.api.yaml
Resolves #481.
The resources are already deployed on DEV, where the upload of a 1GB+ file has been successful.
See [this comment](https://github.com/swisstopo/swissgeol-assets-suite/issues/481#issuecomment-2786202007) for more information on the impact of this change.
> Feature 481: Applikations-Ressourcen für grosse Upload skalieren

- apps/client-asset-sg/project.json
- apps/client-asset-sg/src/app/components/menu-bar-item/menu-bar-item.component.scss
Closes #525 
I also briefly tried replacing `@turf/buffer` by using plain `jsts`, but they do have a similar CJS issue with one subpackage; and bundlesize would get a tiny bit larger, so not really a solution.
> Fix SCSS deprecation warning; allow CJS dependency for @turf/jsts

- .github/workflows/publish-dev.yml
Fixes an issue where the next dev version cannot be determined due to the code responsible for that referencing a non-existent variable.
> Fix `publish-dev` workflow

- apps/server-asset-sg/src/features/asset-edit/asset-edit.repo.ts
- apps/server-asset-sg/src/features/assets/prisma-asset.ts
- apps/server-asset-sg/src/features/files/file-ocr.service.ts
- apps/server-asset-sg/src/features/files/file.repo.spec.ts
- apps/server-asset-sg/src/features/files/file.repo.ts
- apps/server-asset-sg/src/features/files/file.service.ts
- apps/server-asset-sg/src/features/files/files.controller.ts
- apps/server-asset-sg/src/models/AssetDetailFromPostgres.ts
- libs/asset-editor/src/lib/asset-editor.module.ts
- libs/asset-editor/src/lib/components/asset-editor-files/asset-editor-files.component.html
- libs/asset-viewer/src/lib/asset-viewer.module.ts
- libs/asset-viewer/src/lib/components/asset-viewer-files/asset-viewer-files.component.html
- libs/asset-viewer/src/lib/components/asset-viewer-files/asset-viewer-files.component.ts
- libs/client-shared/src/lib/components/file-name.pipe.ts
- libs/client-shared/src/lib/components/index.ts
- libs/persistence/prisma/migrations/20250514120630_file_name_alias/migration.sql
- libs/persistence/prisma/schema.prisma
- libs/shared/src/lib/models/asset-edit.ts
Closes #338 
* I decided to name the field with the filename `fileName` and the alias name `fileNameAlias` and I did only copy those fields that have an alias. Files that are uploaded as-is do not have an alias, so no duplicates needed.
* Note that the naming is _not_ optimal, but `S3Key` would be an even worse choice because we don't want storage technologies tied to our DB name.
* I just assumed that we also need the original file name when downloading an asset
I could not test the full OCR pipeline because that fails locally, but it shouldn't be an issue.
> Implement alias name for files

- apps/client-asset-sg/src/app/i18n/de.ts
- apps/client-asset-sg/src/app/i18n/en.ts
- apps/client-asset-sg/src/app/i18n/fr.ts
- apps/client-asset-sg/src/app/i18n/it.ts
- libs/asset-editor/src/lib/components/asset-editor-page/asset-editor-page.component.html
- libs/asset-editor/src/lib/components/asset-editor-save/asset-editor-save.component.html
- libs/asset-editor/src/lib/components/asset-editor-save/asset-editor-save.component.ts
Fixes #560 
Due to the madness that is the geometry editor, I took @daniel-va 's advice and just disabled the button on this tab, showing a little tooltip option.
> Disable saving on geometry tab as workaround

- libs/asset-editor/src/lib/asset-editor.module.ts
- libs/asset-editor/src/lib/components/asset-editor-tabs/asset-editor-references/add-reference-dialog/add-reference-dialog.component.html
- libs/asset-editor/src/lib/components/asset-editor-tabs/asset-editor-references/add-reference-dialog/add-reference-dialog.component.ts
- libs/client-shared/src/lib/components/index.ts
- libs/client-shared/src/lib/components/select-option/select-option.component.html
- libs/client-shared/src/lib/components/select-option/select-option.component.ts
- libs/client-shared/src/lib/components/select/select.component.html
- libs/client-shared/src/lib/components/select/select.component.ts
Resolves #571.
Depends on #569.
Fixes an issue where the parent asset could be replaced by assigning a new parent asset. This is done by greying out the `main` option in the type selection for new references.
For this to be possible, I had to extend the `asset-sg-select` with the `asset-sg-select-option` component, which enables more fine-grained control over specific select options.
> Bugfix 571: Übergeordnete Verweise nur einmal und Verweis auf sich selber nicht möglich

- apps/server-asset-sg/src/features/assets/asset-edit/asset-edit.repo.ts
Resolves #575.
Once again, this was a bug that was present before the edit redesign, but only now has been noticed.
> Bugfix 575: Asset Edit contacts & references

- apps/sync-asset-sg/.env
- apps/sync-asset-sg/src/core/config.ts
- apps/sync-asset-sg/src/core/sync-extern.service.ts
- apps/sync-asset-sg/src/main.ts
- k8s/swissgeol-sync/secrets.template.yaml
- k8s/swissgeol-sync/templates/cronjob.sync-extern-to-intern.yaml
- k8s/swissgeol-sync/templates/secrets.yaml
- k8s/swissgeol-sync/values.template.yaml
- libs/persistence/prisma/migrations/20250617054456_add_synchronization_table/migration.sql
- libs/persistence/prisma/schema.prisma
Closes #310 
I optimized it only to a certain degree, because batching it further would require a lot of work to guarantee we do not duplicate stuff and have the proper references (without having to permanently fetch all the data from the database).
See notices on the main function as to what is synced and what is not.
For testing purposes:
1. Set `mode=extern` in env
2. Dump your db and import it as e.g. `postgres_extern`
3. Adjust source and target
4. Run the import service
> Implement sync service from extern to intern

- apps/server-asset-sg/src/features/assets/search/asset-search.service.ts
- libs/asset-viewer/src/lib/state/asset-search/asset-search.selector.ts
Fixes the bugs @mPfifi reported in teams (missing filters for topics; non working search terms).
* Missing filters: There was an issue with the rename from `manCatLabels` to `topicCodes`, as well as an issue with items now being parsed as `Map` (which cannot be used directly with `Object.values()`
* Non working search terms: This issue arose because in #579 , `escapeElasticQuery` was reintroduced (which was only present in the deprecated and now-removed `searchOld`): while technically correct, this also prevents @mPfifi's search term (`*tech*`) due to escaped characters. See  #639 for a follow up; this needs further discussion.
> Fix broken filters

- libs/shared/v2/src/lib/models/asset-search/asset-search-query.ts
> Bugfix 656: Bestehende Suche geht bei Wechsel auf Tab "Favoriten" verloren
